export const HOME_USER_SIGN_UP_BEGIN = 'HOME_USER_SIGN_UP_BEGIN';
export const HOME_USER_SIGN_UP_SUCCESS = 'HOME_USER_SIGN_UP_SUCCESS';
export const HOME_USER_SIGN_UP_FAILURE = 'HOME_USER_SIGN_UP_FAILURE';
export const HOME_USER_SIGN_UP_DISMISS_ERROR = 'HOME_USER_SIGN_UP_DISMISS_ERROR';