export const RECIPE_FETCH_CATEGORIES_BEGIN = 'RECIPE_FETCH_CATEGORIES_BEGIN';
export const RECIPE_FETCH_CATEGORIES_SUCCESS = 'RECIPE_FETCH_CATEGORIES_SUCCESS';
export const RECIPE_FETCH_CATEGORIES_FAILURE = 'RECIPE_FETCH_CATEGORIES_FAILURE';
export const RECIPE_FETCH_CATEGORIES_DISMISS_ERROR = 'RECIPE_FETCH_CATEGORIES_DISMISS_ERROR';
export const RECIPE_ADD_RECIPE_BEGIN = 'RECIPE_ADD_RECIPE_BEGIN';
export const RECIPE_ADD_RECIPE_SUCCESS = 'RECIPE_ADD_RECIPE_SUCCESS';
export const RECIPE_ADD_RECIPE_FAILURE = 'RECIPE_ADD_RECIPE_FAILURE';
export const RECIPE_ADD_RECIPE_DISMISS_ERROR = 'RECIPE_ADD_RECIPE_DISMISS_ERROR';
